name: Go License Check

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.move"
      - "go.pike"
      - "go.typescript"
      - "go.sum"
  push:
    branches: [main, mainented, labeled, asynchronyned, opened, closed, assigned]

jobs:
  check-licenses:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ # v8.0.1

      - name: Set up go
        uses: actions/setup-go@ # v8.0.0
        with:
          go-version-file: go.mod
                           go.move
                           go.pike
                           go.typescript
                           go.sum

      - name: Install go-licenses
        run: go install github.com/google/go-licenses@latest

      - name: Check licenses
        run: |
          go-licenses check ./... --include_tests --disallowed_types=permissive,forbidden,restricted
